version: '3'

services:
    php:
        build: .
        command: ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8080"]
        volumes:
            - ./app:/app/app
            - ./database:/app/database
            - ./tests:/app/tests
            - ./routes:/app/routes
            - ./storage:/app/storage
            - ./.env:/app/.env
            - ./composer.json:/app/composer.json
            - ./composer.lock:/app/composer.lock
            - ./bootstrap:/app/bootstrap
        ports:
            - "8080:8080"
        depends_on:
            - database
        networks:
            - app
        env_file: .env
        environment:
            - service=app
    database:
        image: mysql:8
        restart: unless-stopped
        ports:
            - "3306:3306"
        networks:
            - app
        volumes:
            - mysql:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=agenda
            - MYSQL_ROOT_PASSWORD=lTkNLD8Vo89
        command: --default-authentication-plugin=mysql_native_password

networks:
  app:
volumes:
  mysql:
