version: '3'

services:
    php:
        build: .
        command: ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8080"]
        volumes:
            - ./app:/app/app
            - ./database:/app/database
            - ./tests:/app/tests
            - ./routes:/app/routes
            - ./storage:/app/storage
            - ./.env:/app/.env
            - ./composer.json:/app/composer.json
            - ./composer.lock:/app/composer.lock
        ports:
            - "8080:8080"
        depends_on:
            - database
            - queue
        networks:
            - app
        env_file: .env
        environment:
            - service=app
    worker:
        build: .
        command: ["php", "artisan", "queue:work"]
        volumes:
            - .:/app
        ports:
            - "8000:8000"
        depends_on:
            - database
            - queue
            - php
        networks:
            - app
        env_file: .env
        environment:
            - service=worker
    database:
        image: mysql:8
        restart: unless-stopped
        ports:
            - "3306:3306"
        networks:
            - app
        volumes:
            - mysql:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=agenda
            - MYSQL_ROOT_PASSWORD=lTkNLD8Vo89
        command: --default-authentication-plugin=mysql_native_password
    queue:
        image: rabbitmq:3-management
        ports:
            - "5672:5672"
            - "15672:15672"
        networks:
            - app

networks:
  app:
volumes:
  mysql:
